---
- hosts: localhost
  connection: local
  tasks:
    - docker_container:
        name: myhello
        image: roundlifemin/myhello:latest
        state: started
        ports:
          - "80:8080"
...
